PACKAGE_NAME="mechrevo_wujie14pro_perfmode"
PACKAGE_VERSION="1.1"
BUILT_MODULE_NAME[0]="mechrevo_wujie14pro_perfmode"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="make KVERSION=$kernelver"
AUTOINSTALL="yes"
